[project]
name = "mcp-config-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gitpython>=3.1.44",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
